version: '2'
volumes:
    sense-data:
services:
  sensor:
    build: ./sensor
    privileged: true
    restart: always
    volumes:
      - 'sense-data:/data'
  telegraf:
    build: ./telegraf
    restart: always
    cap_add:
      - SYS_ADMIN
